-- Generated by Mocodo 4.1.2

CREATE TABLE Employe (
  PRIMARY KEY (ID_employe),
  ID_employe       VARCHAR(42) NOT NULL,
  nom_employe      VARCHAR(42),
  prenom_employe   VARCHAR(42),
  mail_employe     VARCHAR(42),
  password_employe VARCHAR(42),
  ID_ligue_1       VARCHAR(42) NOT NULL,
  ID_super_Admin   VARCHAR(42) NOT NULL,
  ID_ligue_2       VARCHAR(42) NOT NULL,
  UNIQUE (ID_ligue_1)
);

CREATE TABLE Ligue (
  PRIMARY KEY (ID_ligue),
  ID_ligue  VARCHAR(42) NOT NULL,
  nom_ligue VARCHAR(42)
);

CREATE TABLE Super_Admin (
  PRIMARY KEY (ID_super_Admin),
  ID_super_Admin       VARCHAR(42) NOT NULL,
  nom_super_Admin      VARCHAR(42),
  prenom_super_Admin   VARCHAR(42),
  password_super_Admin VARCHAR(42)
);

ALTER TABLE Employe ADD FOREIGN KEY (ID_ligue_2) REFERENCES Ligue (ID_ligue);
ALTER TABLE Employe ADD FOREIGN KEY (ID_super_Admin) REFERENCES Super_Admin (ID_super_Admin);
ALTER TABLE Employe ADD FOREIGN KEY (ID_ligue_1) REFERENCES Ligue (ID_ligue);
