-- Generated by Mocodo 4.1.2

CREATE TABLE Employe (
  PRIMARY KEY (id_employe),
  id_employe       VARCHAR(42) NOT NULL,
  nom_employe      VARCHAR(42),
  prenom_employe   VARCHAR(42),
  mail_employe     VARCHAR(42),
  password_employe VARCHAR(42),
  id_ligue         VARCHAR(42) NULL,
  id_employe_2     VARCHAR(42) NULL
);

CREATE TABLE Ligue (
  PRIMARY KEY (id_ligue),
  id_ligue   VARCHAR(42) NOT NULL,
  nom_ligue  VARCHAR(42),
  id_employe VARCHAR(42) NULL
);

ALTER TABLE Employe ADD FOREIGN KEY (id_employe_2) REFERENCES Employe (id_employe);
ALTER TABLE Employe ADD FOREIGN KEY (id_ligue) REFERENCES Ligue (id_ligue);

ALTER TABLE Ligue ADD FOREIGN KEY (id_employe) REFERENCES Employe (id_employe);
